import Pricing from "@/components/Pricing";

export default function UpgradePremium() {
  return (
    <div className="py-8 px-6 md:px-12 space-y-2">
      <p className="text-2xl">Upgrade to Premium</p>
      <p className="mb-4">
        Our Basic Plan offers a taste of the experience, but generating plans
        incur costs. If you reached your usage limit, consider upgrading to
        Premium, your wedding plans will also be generated by fancier AI model.
        It’s a one-time payment for seamless, enhanced features!
      </p>

      <Pricing />
    </div>
  );
}
